/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Password;
import javax.swing.JOptionPane;

/**
 *
 * @author baltamar
 */
public class Principal extends javax.swing.JFrame {

    String clave;
    String tamaño;
    Password p, p1;

    public Principal() {
        initComponents();
        cmdMostrar.setEnabled(false);
        cmdCambiarContraseña.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cmdGuardar = new javax.swing.JButton();
        cmdMostrar = new javax.swing.JButton();
        cmdCambiarContraseña = new javax.swing.JButton();
        cmdLimpiar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtPassContraseña = new javax.swing.JPasswordField();
        lblNivelDeSeguridad = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblNumeroDeCaracteres = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultados = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("NIVEL DE SE SEGURDAD DE CONTRASEÑAS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdGuardar.setText("Guardar");
        cmdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 140, -1));

        cmdMostrar.setText("Mostrar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 140, -1));

        cmdCambiarContraseña.setText("Cambiar Contraseña");
        cmdCambiarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCambiarContraseñaActionPerformed(evt);
            }
        });
        jPanel2.add(cmdCambiarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 140, -1));

        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 140, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 160, 150));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos basicos"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPassContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPassContraseñaKeyReleased(evt);
            }
        });
        jPanel3.add(txtPassContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 160, -1));

        lblNivelDeSeguridad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNivelDeSeguridad.setForeground(new java.awt.Color(0, 102, 0));
        jPanel3.add(lblNivelDeSeguridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 160, 20));

        jLabel2.setText("Contraseña:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        lblNumeroDeCaracteres.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel3.add(lblNumeroDeCaracteres, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 160, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 180, 130));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResultados.setEditable(false);
        txtResultados.setColumns(20);
        txtResultados.setRows(5);
        jScrollPane1.setViewportView(txtResultados);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 340, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 360, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPassContraseñaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassContraseñaKeyReleased
        String contraseña, longitud;
        int aux;

        contraseña = txtPassContraseña.getText();
        aux = txtPassContraseña.getText().length();
        longitud = String.valueOf(aux);

        p = new Password(longitud, contraseña);
        p1 = p.NivelDeSeguridad();

        lblNivelDeSeguridad.setText("" + p1.getLongitud());
        lblNumeroDeCaracteres.setText("Número de Caracteres: " + aux);

    }//GEN-LAST:event_txtPassContraseñaKeyReleased

    private void cmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarActionPerformed
        int aux;

        if (txtPassContraseña.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese el campo CONTRASEÑA", "Error", JOptionPane.INFORMATION_MESSAGE);
            txtPassContraseña.requestFocusInWindow();
        } else if (txtPassContraseña.getText().length() > 8) {
            JOptionPane.showMessageDialog(this, "Por favor, Su Contraseña NO puede tener mas de 8 caracteres");
            txtPassContraseña.requestFocusInWindow();
            txtPassContraseña.selectAll();
        } else {
            cmdMostrar.setEnabled(true);
            cmdCambiarContraseña.setEnabled(true);
            cmdLimpiar.setEnabled(false);

            clave = txtPassContraseña.getText();
            aux = txtPassContraseña.getText().length();
            tamaño = String.valueOf(aux);

            Password p = new Password(tamaño, clave);
            JOptionPane.showMessageDialog(this, "Contraseña Guardada Exitosamente", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);

            txtPassContraseña.setText("");
            txtResultados.setText("");
            lblNivelDeSeguridad.setText("");
            lblNumeroDeCaracteres.setText("");
            txtPassContraseña.setEnabled(false);
            cmdGuardar.setEnabled(false);
            cmdCambiarContraseña.setEnabled(false);

        }


    }//GEN-LAST:event_cmdGuardarActionPerformed

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed
        cmdGuardar.setEnabled(false);
        cmdLimpiar.setEnabled(true);
        String aux;

        aux = "Contraseña:" + "\n" + clave + "\n\n"
                + "Numero de caracteres:" + "\n" + tamaño + "\n\n"
                + "Nivel de seguridad: " + "\n" + p1.getLongitud();

        txtResultados.setText(aux);
        cmdCambiarContraseña.setEnabled(true);

    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void cmdCambiarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCambiarContraseñaActionPerformed
        p1.setContraseña(clave);

        lblNumeroDeCaracteres.setText("Ingrese Nueva Clave");
        cmdGuardar.setEnabled(true);
        cmdCambiarContraseña.setEnabled(false);
        cmdMostrar.setEnabled(false);
        txtPassContraseña.setEnabled(true);

        txtPassContraseña.requestFocusInWindow();
        txtResultados.setText("");
    }//GEN-LAST:event_cmdCambiarContraseñaActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed
        txtPassContraseña.setText("");
        txtResultados.setText("");
        lblNivelDeSeguridad.setText("");
        lblNumeroDeCaracteres.setText("");
        txtPassContraseña.requestFocusInWindow();
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCambiarContraseña;
    private javax.swing.JButton cmdGuardar;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNivelDeSeguridad;
    private javax.swing.JLabel lblNumeroDeCaracteres;
    private javax.swing.JPasswordField txtPassContraseña;
    private javax.swing.JTextArea txtResultados;
    // End of variables declaration//GEN-END:variables
}
